# Generated by Django 4.2.7 on 2024-05-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strength_bnb',
            name='commission',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='strength_bnb',
            name='max_out',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='strength_bnb',
            name='min_out',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='strength_netbo',
            name='commission',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='strength_netbo',
            name='max_out',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='strength_netbo',
            name='min_out',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
