# Generated by Django 4.2.7 on 2024-05-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strength',
            name='taim',
            field=models.FloatField(default=0),
        ),
    ]
