# Generated by Django 4.2.7 on 2024-05-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_strength_taim'),
    ]

    operations = [
        migrations.AddField(
            model_name='strength',
            name='default_netbo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
