# Generated by Django 4.2.7 on 2024-05-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_strength_default_netbo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneyoutbnb',
            old_name='balance_bnb',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='moneyoutnetbo',
            old_name='balance_netbo',
            new_name='balance',
        ),
        migrations.AlterField(
            model_name='strength',
            name='taim',
            field=models.FloatField(default=0.5),
        ),
    ]
